version: '3.8'

services:

  # Backend API
  smartbrain2_api:
    container_name: backend_api
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain2_api
    environment:
      DB_VENDOR: postgres
      POSTGRES_URI: postgres://jill:theodorebear@postgres:5432/smartbrain2-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
     - ./:/usr/src/smartbrain2_api
     - /usr/src/smartbrain2_api/node_modules

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: jill
      POSTGRES_PASSWORD: theodorebear
      POSTGRES_DB: smartbrain2-docker
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
